---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Center"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "company"
  description: "Center of control"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "user"
  description: "Center of control"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /company:
    post:
      tags:
      - "company"
      summary: "Add a new company"
      description: ""
      operationId: "addCompany"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Company"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "Company"
    put:
      tags:
      - "company"
      summary: "Update  company"
      description: ""
      operationId: "updateCompany"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Company"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "Company"
  /company/delete/{id}:
    delete:
      tags:
      - "company"
      summary: "Delete Company"
      description: ""
      operationId: "deleteCompany"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id for search"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Company"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "Company"
  /company/byId/{id}:
    get:
      tags:
      - "company"
      summary: "Add a new company"
      description: ""
      operationId: "getCompany"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id for search"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Company"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "Company"
  /company/byText/{text}:
    get:
      tags:
      - "company"
      summary: "get Company for text"
      description: ""
      operationId: "getCompanyText"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "text"
        in: "path"
        description: "id for search"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Company"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "Company"
definitions:
  Company:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      fiscal:
        $ref: "#/definitions/Company_fiscal"
      contact:
        $ref: "#/definitions/Company_contact"
      otherData:
        $ref: "#/definitions/Company_otherData"
    example:
      fiscal:
        rsocial: "rsocial"
        address: "address"
        province: "province"
        document: "document"
        postalCode: "postalCode"
        population: "population"
      otherData:
        sector: "sector"
      contact:
        contacPerson: "contacPerson"
        telephone: "telephone"
        email: "email"
      id: 0
  Company_fiscal:
    type: "object"
    properties:
      rsocial:
        type: "string"
      document:
        type: "string"
      address:
        type: "string"
      population:
        type: "string"
      province:
        type: "string"
      postalCode:
        type: "string"
    example:
      rsocial: "rsocial"
      address: "address"
      province: "province"
      document: "document"
      postalCode: "postalCode"
      population: "population"
  Company_contact:
    type: "object"
    properties:
      telephone:
        type: "string"
      contacPerson:
        type: "string"
      email:
        type: "string"
    example:
      contacPerson: "contacPerson"
      telephone: "telephone"
      email: "email"
  Company_otherData:
    type: "object"
    properties:
      sector:
        type: "string"
    example:
      sector: "sector"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
